//Java strings program...
public class MyStrings {
	public static void main(String args[]){
		//printing the length of string...
		String myFullName = "Qozeem Banji Odeniran";
		System.out.println("My name is "+myFullName+", and it's "+myFullName.length()+" characters long.\n");
		//printing myFullName in uppercase...
		System.out.println(myFullName.toUpperCase()+" - This is my name is uppercase.\n");
		//Printing myFullName in lower case...
		System.out.println(myFullName.toLowerCase()+" - This is my name in lowercase\n");
		//Finding characters in a string...
		System.out.println(myFullName.indexOf(" ")); //output the index of the first whitespace...(6 expected)
	}
}
